version: '3.4'

services:

  #Database
  aspnetmicroservices.catalogdb:
    image: mongo

  aspnetmicroservices.observabilitydb:
    image: redis:7.0

  aspnetmicroservices.basketdb:
    image: redis:alpine

  aspnetmicroservices.discountdb:
    image: postgres

  aspnetmicroservices.orderdb:
    image: mcr.microsoft.com/mssql/server:2019-latest


  #Services
  aspnetmicroservices.catalog.api:
    image: aspnetmicroservices.catalog.api.image
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
  
  aspnetmicroservices.basket.api:
    image: aspnetmicroservices.basket.api.image
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  aspnetmicroservices.discount.api:
    image: aspnetmicroservices.discount.api.image
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile

  aspnetmicroservices.discount.grpc:
    image: aspnetmicroservices.discount.grpc.image
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile

  aspnetmicroservices.ordering.api:
    image: aspnetmicroservices.ordering.api.image
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile

  #Observability
  aspnetmicroservices.jaeger:
    image: jaegertracing/all-in-one:1.49

  aspnetmicroservices.rabbitmq:
    image: rabbitmq:3.12.2-management

  aspnetmicroservices.elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1 
    
  aspnetmicroservices.kibana:
    image: docker.elastic.co/kibana/kibana:8.8.1

  aspnetmicroservices.metric.api:
    image: metric.api.image
    build:
     context: .
     dockerfile: Shared/Metric.API/Dockerfile

  aspnetmicroservices.prometheus:
    image: prom/prometheus:v2.37.9
    volumes: 
     - ./prometheus.yml:/etc/prometheus/prometheus.yml

  #Tools
  #pgadmin:
  #  image: dpage/pgadmin4  


  #zipkin:
  #  image: openzipkin/zipkin:2.24








volumes:
  aspnetmicroservices_mongo_data:
  aspnetmicroservices_postgres_data:
  #pgadmin_data:
  aspnetmicroservices_elastic_db:
     



